# Generated by Django 2.1.7 on 2019-03-09 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 17, 28, 1, 690089, tzinfo=utc), null=True),
        ),
    ]
