# Generated by Django 2.2a1 on 2019-03-23 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_auto_20190314_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 7, 3, 10, 176695, tzinfo=utc), null=True),
        ),
    ]
