# Generated by Django 2.2a1 on 2019-04-18 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0007_auto_20190418_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 14, 0, 46, 495883, tzinfo=utc), null=True),
        ),
    ]
