# Generated by Django 2.1.7 on 2019-03-08 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actType', models.CharField(max_length=1000000000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000000000)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=1000000000)),
                ('image', models.CharField(max_length=4294967296)),
                ('upvotes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 3, 8, 17, 36, 47, 627614, tzinfo=utc), null=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.Acts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialmedia.CustomUser')),
            ],
        ),
    ]
