# Generated by Django 2.2a1 on 2019-03-14 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_auto_20190309_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 15, 23, 26, 116776, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(default='anonymous', max_length=1000000000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
