# Generated by Django 2.2a1 on 2019-04-18 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0007_auto_20190418_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 13, 59, 43, 22698, tzinfo=utc), null=True),
        ),
    ]
