# Generated by Django 2.2a1 on 2019-04-18 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0008_auto_20190418_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 15, 5, 35, 292769, tzinfo=utc), null=True),
        ),
    ]
